# Generated by Django 4.2.5 on 2023-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat/media/'),
        ),
    ]
