# Generated by Django 4.2.5 on 2023-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
